Description of inves_liver
inves_liver
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
select3d SELECT3D(H) Determines the selected point in 3-D data space.
surf2mesh
new_vertices displacem_strain_stress - calculate the new coordinates of deformed
read_wobj Read the objects from a Wavefront OBJ file
surf2mesh
This function is called by:
SOURCE CODE
clear all;
clc;
% % anoigma tou Obj arxeiou me thn sunartish read_wobj
%
% OBJ=read_wobj('FJ3153_BP7865_FMA7488_Xiphoid process.obj');
%
% % FV.vertices=OBJ.vertices;
% %     FV.faces=OBJ.objects(3).data.vertices;
% %     figure(3), patch(FV,'facecolor',[1 0 0]); camlight
% % metegora twn suntetagmenwn twn dianismatwn(x,y,z
%
% x = OBJ.vertices(:,1);
% y = OBJ.vertices(:,2);
% z = OBJ.vertices(:,3);
%
% % allagh ths montelopoihshw apo trigwna se tetraedra
% dt = delaunayTriangulation(x,y,z);
% % ta nea elements pou dhmiourgithikan
% nodes_per_elem(:,:)= dt(:,:);
% % oi kainourgies suntetagmenes
% corr(:,:) = [x(:) y(:) z(:)];
%
% % apeikonish tou arxikou montelou
%
%
% % FV.vertices=OBJ.vertices;
% %     FV.faces=nodes_per_elem(:,:);
% %     figure(4), patch(FV,'facecolor',[1 0 0]); camlight
% % arithmos twn kombwn
% numb_nodes=size(corr,1);
%
% %arithmos twn stoixeivn
% elements=size(nodes_per_elem,1);
%
% load liver.mat
%
 OBJ=read_wobj('DL3D_LiverExternal.obj');
x = OBJ.vertices(:,1);
y = OBJ.vertices(:,2);
z = OBJ.vertices(:,3);
m=size(x,1);
v=[x y z];
f=OBJ.objects(3).data.vertices;
[node,elem,face]=surf2mesh(v,f,[1 1 1],[100 100 100],0.1,25);
% corr=corr;
% faces=face;
% nodes_per_elem=nodes_per_elem;
% x=(corr*0.01);
nodes_per_elem=[elem(:,1) elem(:,2) elem(:,3) elem(:,4)] ;
corr= 0.05*node;
% corr=x;
faces=[face(:,1) face(:,2) face(:,3)];
numb_nodes=size(corr,1);
elements=size(nodes_per_elem,1);
figure (1)
  tetramesh(nodes_per_elem,corr);
  axis([-0.25 0.25 -0.25 0.25 -0.25 0.25])
% tetramesh(nodes_per_elem,corr,'Facecolor',vector);
%  axis([-2.5 2.5 -2.5 2.5 -2.5 2.5 ])
 camlight
% view(270,0);
% axis([-0.05 0.05 -0.05 0.1 -0.1 0.1])
%  h=tetramesh(nodes_per_elem,corr);
% ax1=get(h,'Children');
%    -0.0487    0.0960   -0.0129    0.1585    0.0402    0.1315
% axis tight
% limitb=axis;
% clear axis;
%material matrix
% E = 0.0019; % shell material elasticity constant
% E=(0.5935*10000);
 E=(6*1000);
% E=0.5935;
v = 0.4; % shell material poisson ratio
C = E / ((1+v)*(1-2*v))*[1-v ,  v , v ,  0      ,    0     ,   0      ;
                          v  , 1-v, v ,  0      ,    0     ,   0      ;
                          v  ,  v ,1-v,  0      ,    0     ,   0      ;
                          0  ,  0 , 0 ,(1-2*v)/2,    0     ,   0      ;
                          0  ,  0 , 0 ,   0     , (1-2*v)/2,   0      ;
                          0  ,  0 , 0 ,  0      ,    0     ,(1-2*v)/2];
%arxikopoihsh twn pinakwn akampsias kai paramorfwsewn
Ke = zeros(12,12,elements);
B = zeros(6,12,elements);
% modelopoiisi from finite element modeling in surgery simulation was
% written by Morten Bro-Nielsen
for n = 1:elements
%  ind=nodes_per_elem(n,:)';
%  ind3=3*ind(:,[1 1 1]) - [2 1 0;2 1 0;2 1 0;2 1 0];
%  ind3=ind3';
P=zeros(4);
A1=zeros(3);
A2=zeros(3);
A3=zeros(3);
A4=zeros(3);
B1=zeros(3);
B2=zeros(3);
B3=zeros(3);
B4=zeros(3);
C1=zeros(3);
C2=zeros(3);
C3=zeros(3);
C4=zeros(3);
D1=zeros(3);
D2=zeros(3);
D3=zeros(3);
D4=zeros(3);
a1=0;
a2=0;
a3=0;
a4=0;
b1=0;
b2=0;
b3=0;
b4=0;
c1=0;
c2=0;
c3=0;
c4=0;
d1=0;
d2=0;
d3=0;
d4=0;
Vol=0;
gNode = corr(nodes_per_elem(n,:),:);
V1=[ 1 1 1 1;
     gNode(1,1) gNode(2,1) gNode(3,1) gNode(4,1);
     gNode(1,2) gNode(2,2) gNode(3,2) gNode(4,2);
     gNode(1,3) gNode(2,3) gNode(3,3) gNode(4,3)];
%    V2=[(gNode(1,1)-gNode(4,1)) (gNode(2,1)-gNode(4,1)) (gNode(3,1)-gNode(4,1));
%      (gNode(1,2)-gNode(4,2)) (gNode(2,2)-gNode(4,2)) (gNode(3,2)-gNode(4,2));
%       (gNode(1,3)-gNode(4,3)) (gNode(2,3)-gNode(4,3)) (gNode(3,3)-gNode(4,3))];
 Vol=abs((1/6)*det(V1));
%
%  Vol1=abs((1/6)*det(V2));
 P=inv(V1);
 Q=(6*Vol)*P;
 a1=Q(1,1);
 a2=Q(2,1);
 a3=Q(3,1);
 a4=Q(4,1);
 b1=Q(1,2);
 b2=Q(2,2);
 b3=Q(3,2);
 b4=Q(4,2);
 c1=Q(1,3);
 c2=Q(2,3);
 c3=Q(3,3);
 c4=Q(4,3);
 d1=Q(1,4);
 d2=Q(2,4);
 d3=Q(3,4);
 d4=Q(4,4);
  B(:,:,n)= (1/(6*Vol))* [b1, 0, 0, b2, 0, 0, b3, 0, 0, b4, 0, 0;
                      0,  c1, 0, 0, c2, 0, 0, c3, 0, 0, c4, 0;
                      0, 0, d1, 0, 0, d2, 0, 0, d3, 0, 0, d4;
                      c1, b1, 0, c2, b2, 0, c3, b3, 0, c4, b4, 0;
                      0, d1, c1, 0, d2, c2, 0, d3, c3, 0, d4, c4;
                      d1, 0, b1, d2, 0, b2, d3, 0, b3, d4, 0, b4];
    %pinakas  akampsias
  Ke(:,:,n)= Vol *B(:,:,n)' * C* B(:,:,n);
%       K(ind3,ind3)=K(ind3,ind3)+Ke(:,:,n);
end
 Re = zeros(numb_nodes,3);
 Re(:,:)= corr(:,:);
%  Re(36,:)=[0 0 0];
%  Re(37,1)=0;
%  Re(37,2)=0;
%  Re(37,3)=0;
%
 Re(39,:)=[0 0 0];
 Re(40,:)=[0 0 0];
 Re(59,:)=[0 0 0];
%  Re(111,:)=[0 0 0];
%  Re(119,:)=[0 0 0];
%  Re(217,:)=[0 0 0];
%  Re(229,:)=[0 0 0];
%  Re(295,:)=[0 0 0];
%  Re(316,:)=[0 0 0];
%
%
%
%  Re(20,:)=[0 0 0];
%  Re(21,:)=[0 0 0];
%
%
%  Re(110,:)=[0 0 0];
 nom = size(Re,2);
%arithmisi twn bathwn eleutherias
item = 0;
for i = 1:numb_nodes;
    for j = 1:nom;
        if Re(i,j) ~= 0;
            item = item +1;
            Re(i,j) = item;
        end
    end
 end
%dimiourgia tou connectivity array
for i = 1:elements
    R(i,:) = [Re(nodes_per_elem(i,1),:) Re(nodes_per_elem(i,2),:) Re(nodes_per_elem(i,3),:) Re(nodes_per_elem(i,4),:)];
end
% upologismos tou katholikou pinaka akamsias
Kg(item,item)=0;
%dhmiourgia tou katholikou pinaka akapsias
for x = 1:elements;
    for sat = 1:12;
        for sut = 1:12;
            if (R(x,sat) ~= 0)
                if (R(x,sut) ~= 0);
                    Kg(R(x,sut),R(x,sat)) = Kg(R(x,sut),R(x,sat)) + Ke(sat,sut,x);
                end
            end
        end
    end
end
%
%
%
%
%
%
%
%
%
%
%
prompt = {'arithos dinamewn pou thelete na askhthoun sto swma:'};
dlg_title = 'Input';
num_lines = 1;
answer = inputdlg(prompt,dlg_title,num_lines);
F(item) = 0;
a = str2num(answer{1});
% FV.vertices=corr;
% FV.faces=nodes_per_elem;
% figure(1);
for i=1:a;
%  h=patch(FV,'facecolor',[0.9 0 0]); camlight
% % set(h, 'ButtonDownFcn',@buttonDownCallback)
set(gcf,'Pointer','fullcross')
%select3dtool
%zoom(10);
disp('Click anywhere on the surface, then hit return')
pause
[p v vi face facei] = select3d;
marker1 = line('xdata',p(1),'ydata',p(2),'zdata',p(3),'marker','o',...
    'erasemode','xor','markerfacecolor','k');
% marker2 = line('xdata',v(1),'ydata',v(2),'zdata',v(3),'marker','o',...
%     'erasemode','xor','markerfacecolor','k');
% marker2 = line('erasemode','xor','xdata',face(1,:),'ydata',face(2,:),...
%     'zdata',face(3,:),'linewidth',10);
disp(sprintf('\nYou clicked at\nX: %.2f\nY: %.2f\nZ: %.2f',p(1),p(2),p(3)'))
disp(sprintf('\nThe nearest vertex is\nX: %.2f\nY: %.2f\nZ: %.2f',v(1),v(2),v(3)'))
%
% [p1,p2]=find(corr==v(1));
% [p3,p4]=find(corr==v(2));
% [p5,p6]=find(corr==v(3));
% if (p1~=p3)&&(p1~=p5);
% disp('error with the point')
% end
[p1,p2]=find(corr==v(1));
[p3,p4]=find(corr==v(2));
if p1~=p3;
disp('error with the point')
end
    prompt1={'katefthinsi pou thelete x or y or z','metro tis dinameis'};
    dlg_title = 'stoixeia dimamevn';
    num_lines = 1;
    apote= inputdlg(prompt1,dlg_title,num_lines);
    numb_1=str2num(apote{1});
    numb_2=str2num(apote{2});
    F(Re(p1,numb_1) )= numb_2;
end
%dinameis pou askounte sto swma
%askhsh dunamewn stouw kombous kai se poia kateuthinsei x,y,z
%F(item) = 0;
%F(Re(250,2))  = 1000000;
%F(Re(65,3))  = -1000;
%F(Re(282,2)) = 1000000;
%F(Re(352,1)) = -100000;
%F(Re(372,1)) = -10000;
%F(Re(442,3)) = -10000;
%F(Re(451,2)) = -10000;
%F(Re(450,2)) = -10000;
%upologismos twn metatwpisewn
%elegxos an o pinakas akapsias einai swsta kataskeuasmenos
% equation=size(Kg);
% if equation(1) ~= rank(Kg)
%     display('This system stiffness matrix is badly scaled')
%     error('Control system support boundary conditions')
% else
    %upologismou twn metatopisewn twn kombwn
    D = inv(Kg) * F';
% end
for  i = 1:elements;
    for m = 1:12;
        s = R(i, m);
        if s ~=0; Hu(i,m) = D(s) ;
        else      Hu(i,m)  = 0   ;
        end
    end
end
%upologismos strain(tropes) strain=B*diplacements(ux,uy,uz)
e=zeros(6,1,elements);
for i=1:elements;
    e(:,:,i)= B(:,:,i)* Hu(i,:)';
end
%upologismos stress(taseis) stress=C*strain
str=zeros(6,1,elements);
for p=1:elements;
    str(:,:,p)=C*e(:,:,p);
end
dis=zeros(numb_nodes,3);
%oi metatopiseis kathe kombou me thn seira pou briskontai ston corr pinaka
for  i = 1:elements;
    for j=1:4;
        if j==1;
            b=1;
            dis(nodes_per_elem(i,j),:)= [Hu(i,b) Hu(i,b+1) Hu(i,b+2)];
        else if j==2;
                b=4;
                dis(nodes_per_elem(i,j),:)= [Hu(i,b) Hu(i,b+1) Hu(i,b+2)];
            else if j==3;
                    b=7;
                    dis(nodes_per_elem(i,j),:)= [Hu(i,b) Hu(i,b+1) Hu(i,b+2)];
                else
                    b=10;
                    dis(nodes_per_elem(i,j),:)= [Hu(i,b) Hu(i,b+1) Hu(i,b+2)];
                end
            end
        end
    end
end
size(Hu);
%upologismos twn suntetagmenwn twn paramorfwmenwn kombwn
%upologismos tou neou pinaka new_vertices gia thn apeikonish tou
%paramorfwmenou montelou
new_vertices=zeros(numb_nodes,3);
new_vertices(:,:)= corr(:,:) + dis(:,:);
aa=size(new_vertices);
% figure(2);
% tetramesh(nodes_per_elem,new_vertices);
% hold on;
% tetramesh(nodes_per_elem,corr,'Facecolor','m');
% % axis tight
% % limits=axis;
% %
% figure(2)
% tetramesh(nodes_per_elem,corr,'Facecolor','m');
% tetramesh(nodes_per_elem,corr);
% view(270,0);
% camlight;
% figure(3)
% tetramesh(nodes_per_elem,new_vertices);
% camlight;
% view(270,0);
figure(2)
trimesh(faces,corr(:,1),corr(:,2),corr(:,3));
view(270,0);
camlight;
figure(3)
trimesh(faces,new_vertices(:,1),new_vertices(:,2),new_vertices(:,3));
view(270,0);
camlight;
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%