/* Auto-generated by genmsg_cpp for file /home/delk/fuerte_workspace/sandbox/gt-ros-pkg/gt-ros-pkg.hrl/hrl_hardware_drivers/phantom_omni/msg/PhantomButtonEvent.msg */
#ifndef PHANTOM_OMNI_MESSAGE_PHANTOMBUTTONEVENT_H
#define PHANTOM_OMNI_MESSAGE_PHANTOMBUTTONEVENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace phantom_omni
{
template <class ContainerAllocator>
struct PhantomButtonEvent_ {
  typedef PhantomButtonEvent_<ContainerAllocator> Type;

  PhantomButtonEvent_()
  : grey_button(0)
  , white_button(0)
  {
  }

  PhantomButtonEvent_(const ContainerAllocator& _alloc)
  : grey_button(0)
  , white_button(0)
  {
  }

  typedef int32_t _grey_button_type;
  int32_t grey_button;

  typedef int32_t _white_button_type;
  int32_t white_button;


  typedef boost::shared_ptr< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PhantomButtonEvent
typedef  ::phantom_omni::PhantomButtonEvent_<std::allocator<void> > PhantomButtonEvent;

typedef boost::shared_ptr< ::phantom_omni::PhantomButtonEvent> PhantomButtonEventPtr;
typedef boost::shared_ptr< ::phantom_omni::PhantomButtonEvent const> PhantomButtonEventConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace phantom_omni

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fb77877e6b639935c3360838062f05f0";
  }

  static const char* value(const  ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfb77877e6b639935ULL;
  static const uint64_t static_value2 = 0xc3360838062f05f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "phantom_omni/PhantomButtonEvent";
  }

  static const char* value(const  ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 grey_button\n\
int32 white_button\n\
\n\
";
  }

  static const char* value(const  ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.grey_button);
    stream.next(m.white_button);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PhantomButtonEvent_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::phantom_omni::PhantomButtonEvent_<ContainerAllocator> & v) 
  {
    s << indent << "grey_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grey_button);
    s << indent << "white_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.white_button);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PHANTOM_OMNI_MESSAGE_PHANTOMBUTTONEVENT_H

